config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :administrators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/student.rb
class Student < ApplicationRecord
  validates :student_id, presence: true, numericality: { greater_than_or_equal_to: 100000, less_than_or_equal_to: 999999, only_integer: true, message: "must be an id within 100000-999999"}
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
  validates :encrypted_password, presence: true, length: { minimum: 8, message: "must be at least 8 characters long" }
  validates :class_period, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 8, only_integer: true, message: "must be an number within 1-8"}
  validates :name, presence: {message: "a name is required"}
  validates :teacher_id, presence: {message: "teacher id is required"}
  belongs_to :teacher
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :student_id, :class_period, :teacher_id, :email, :encrypted_password, :class_period)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.number_field :student_id %>
  </div>

  <div>
    <%= form.label :class_period, style: "display: block" %>
    <%= form.number_field :class_period %>
  </div>

  <div>
    <%= form.label :teacher_id, style: "display: block" %>
    <%= form.text_field :teacher_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= student.student_id %>
  </p>

  <p>
    <strong>Class period:</strong>
    <%= student.class_period %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= student.teacher_id %>
  </p>

</div>

app/views/students/edit.html.erb
<% content_for :title, "Editing student" %>

<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Students" %>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<% content_for :title, "New student" %>

<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>