config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :administrators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :teacher_id, presence: true, numericality: { greater_than_or_equal_to: 100000, less_than_or_equal_to: 999999, only_integer: true, message: "must be an id within 100000-999999"}
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
  validates :encrypted_password, presence: true, length: { minimum: 8, message: "must be at least 8 characters long" }
  validates :name, presence: {message: "a name is required"}
  validates :administrator_id, presence: {message: "administrator id is required"}
  belongs_to :administrator
  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy!

    respond_to do |format|
      format.html { redirect_to teachers_path, status: :see_other, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :teacher_id, :administrator_id, :email, :encrypted_password)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :teacher_id, style: "display: block" %>
    <%= form.number_field :teacher_id %>
  </div>

  <div>
    <%= form.label :administrator_id, style: "display: block" %>
    <%= form.text_field :administrator_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p>
    <strong>Name:</strong>
    <%= teacher.name %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= teacher.teacher_id %>
  </p>

  <p>
    <strong>Administrator:</strong>
    <%= teacher.administrator_id %>
  </p>

</div>

app/views/teachers/edit.html.erb
<% content_for :title, "Editing teacher" %>

<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Teachers" %>

<h1>Teachers</h1>

<div id="teachers">
  <% @teachers.each do |teacher| %>
    <%= render teacher %>
    <p>
      <%= link_to "Show this teacher", teacher %>
    </p>
  <% end %>
</div>

<%= link_to "New teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<% content_for :title, "New teacher" %>

<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>

<div>
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
</div>