config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :administrators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: %i[ show edit update destroy ]

  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1 or /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators or /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: "Administrator was successfully created." }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: "Administrator was successfully updated." }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy
    @administrator.destroy!

    respond_to do |format|
      format.html { redirect_to administrators_path, status: :see_other, notice: "Administrator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrator_params
      params.require(:administrator).permit(:name, :school_name, :administrator_id)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <p>
    <strong>Name:</strong>
    <%= administrator.name %>
  </p>

  <p>
    <strong>School name:</strong>
    <%= administrator.school_name %>
  </p>

  <p>
    <strong>Administrator:</strong>
    <%= administrator.administrator_id %>
  </p>

</div>

app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :school_name, style: "display: block" %>
    <%= form.text_field :school_name %>
  </div>

  <div>
    <%= form.label :administrator_id, style: "display: block" %>
    <%= form.number_field :administrator_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<% content_for :title, "Editing administrator" %>

<h1>Editing administrator</h1>

<%= render "form", administrator: @administrator %>

<br>

<div>
  <%= link_to "Show this administrator", @administrator %> |
  <%= link_to "Back to administrators", administrators_path %>
</div>

app/views/administrators/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Administrators" %>

<h1>Administrators</h1>

<div id="administrators">
  <% @administrators.each do |administrator| %>
    <%= render administrator %>
    <p>
      <%= link_to "Show this administrator", administrator %>
    </p>
  <% end %>
</div>

<%= link_to "New administrator", new_administrator_path %>

app/views/administrators/new.html.erb
<% content_for :title, "New administrator" %>

<h1>New administrator</h1>

<%= render "form", administrator: @administrator %>

<br>

<div>
  <%= link_to "Back to administrators", administrators_path %>
</div>

app/views/administrators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @administrator %>

<div>
  <%= link_to "Edit this administrator", edit_administrator_path(@administrator) %> |
  <%= link_to "Back to administrators", administrators_path %>

  <%= button_to "Destroy this administrator", @administrator, method: :delete %>
</div>